export const POST_FORGOT_PASSWORD_REQUEST: "POST_FORGOT_PASSWORD_REQUEST" = "POST_FORGOT_PASSWORD_REQUEST";
export const POST_FORGOT_PASSWORD_SUCCESS: "POST_FORGOT_PASSWORD_SUCCESS" = "POST_FORGOT_PASSWORD_SUCCESS";
export const POST_FORGOT_PASSWORD_FAILED: "POST_FORGOT_PASSWORD_FAILED" = "POST_FORGOT_PASSWORD_FAILED";