export const POST_REFRESH_TOKEN_REQUEST: "POST_REFRESH_TOKEN_REQUEST" = "POST_REFRESH_TOKEN_REQUEST";
export const POST_REFRESH_TOKEN_SUCCESS: "POST_REFRESH_TOKEN_SUCCESS" = "POST_REFRESH_TOKEN_SUCCESS";
export const POST_REFRESH_TOKEN_FAILED: "POST_REFRESH_TOKEN_FAILED" = "POST_REFRESH_TOKEN_FAILED";