export const AUTH_TOKENS_REQUEST = "AUTH_TOKENS_REQUEST";
export const SET_AUTH_TOKENS = "SET_AUTH_TOKENS";
export const UNSET_AUTH_TOKENS = "UNSET_AUTH_TOKENS";
export const AUTH_TOKENS_SUCCESS = "AUTH_TOKENS_SUCCESS";
export const AUTH_TOKENS_FAILED = "AUTH_TOKENS_FAILED";