// Модальное окно оформления заказа
export const SET_MODAL_ORDER: "SET_MODAL_ORDER" = "SET_MODAL_ORDER";
export const UNSET_MODAL_ORDER: "UNSET_MODAL_ORDER" = "UNSET_MODAL_ORDER"; // Под вопросом, может не нужен
// Отправка заказа на сервер
export const POST_ORDER_REQUEST: "POST_ORDER_REQUEST" = "POST_ORDER_REQUEST";
export const POST_ORDER_SUCCESS: "POST_ORDER_SUCCESS" = "POST_ORDER_SUCCESS";
export const POST_ORDER_FAILED: "POST_ORDER_FAILED" = "POST_ORDER_FAILED";
// Получение заказа с сервера по id
export const GET_ORDER_REQUEST: "GET_ORDER_REQUEST" = "GET_ORDER_REQUEST";
export const GET_ORDER_FEED_SUCCESS: "GET_ORDER_FEED_SUCCESS" = "GET_ORDER_FEED_SUCCESS";
export const GET_ORDER_PROFILE_SUCCESS: "GET_ORDER_PROFILE_SUCCESS" = "GET_ORDER_PROFILE_SUCCESS";
export const GET_ORDER_FAILED: "GET_ORDER_FAILED" = "GET_ORDER_FAILED";
// Открытие модальных окон с заказом для ленты заказов и профиля
export const SET_FEED_MODAL_ORDER: "SET_FEED_MODAL_ORDER" = "SET_FEED_MODAL_ORDER";
export const UNSET_FEED_MODAL_ORDER: "UNSET_FEED_MODAL_ORDER" = "UNSET_FEED_MODAL_ORDER";
export const SET_PROFILE_MODAL_ORDER: "SET_PROFILE_MODAL_ORDER" = "SET_PROFILE_MODAL_ORDER";
export const UNSET_PROFILE_MODAL_ORDER: "UNSET_PROFILE_MODAL_ORDER" = "UNSET_PROFILE_MODAL_ORDER";