export const SET_MODAL_ORDER: "SET_MODAL_ORDER" = "SET_MODAL_ORDER";
export const UNSET_MODAL_ORDER: "UNSET_MODAL_ORDER" = "UNSET_MODAL_ORDER"; // Под вопросом, может не нужен
export const POST_ORDER_REQUEST: "POST_ORDER_REQUEST" = "POST_ORDER_REQUEST";
export const POST_ORDER_SUCCESS: "POST_ORDER_SUCCESS" = "POST_ORDER_SUCCESS";
export const POST_ORDER_FAILED: "POST_ORDER_FAILED" = "POST_ORDER_FAILED";